title: "蓝燕光"
domain: lanyg.com
baseurl: /
production_url: http://lanyg.com
disqus :
  short_name : yanguanglan
author :
  name : "蓝燕光"
  email : yang0guang.lan[at]gmail.com
  github : yanguanglan
  avatar: http://www.gravatar.com/avatar/ad0fd0749f43f53f8be2cc2143da7d1f?s=80&d=mm&r=g